---
language: node_js
sudo: false
dist: trusty
node_js:
  - "10"

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache
    - node_modules

env:
  global:
    - JOBS=1

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install

before_script:
  - ember version
  - yarn list | grep ember-source
  - yarn list | grep ember-data

notifications:
  email: false

stages:
  - test
  - additional tests
  - fastboot tests
  - versioned tests
  - deploy

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup

jobs:
  fail_fast: true

  include:
    - stage: test
      env: NAME=test
      script: yarn test

    - stage: additional tests
      env: NAME=floating dependencies
      install: yarn install --no-lockfile --non-interactive
      script: yarn test

    - stage: fastboot tests
      node_js: "10"
      env: NAME=fastboot tests
      script: yarn test:fastboot

    - stage: versioned tests
    - env: EMBER_TRY_SCENARIO=ember-lts-3.12
      env: EMBER_TRY_SCENARIO=ember-lts-3.16
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default

    - stage: deploy
      if: (branch = master OR tag IS present) AND type = push
      env: NAME=deploy
      script: node_modules/.bin/ember deploy production

    - stage: npm release
      install: skip
      before_script: skip
      script: skip
      deploy:
        provider: npm
        email: sam.selikoff@gmail.com
        api_key:
          secure: eZu7zw8mTnUsKkqF+7HVvaT12A/6DSeA+opUv/ZQeyfkkthwVY5LlZT4OdsLdqXt6YtwU4yOlBM740ApaHHeLz0vjOK04GgtnRVhX4byW6iRMMIdW1Unz6aYAiOzJqUXe4gWZ/PMFKtIaprmz0aV4kX97y05mkF0kiTymVqcStbwISTuEDWkt4Wxu/4BBScxl+48RRZaruLktdLDogYttUY989uhtfxYFeRts9RymbICNirPDlBWq4bu1AU+/Yrf36vnLRVtVp89ctZ+APRJddQukw/6eaJjCqnGwnTy51DXlV81Sr+cIIX5ille26wCVreDtIreQ8UxsdbQpAKt6Txyeg5EKRE7aIqC7NCKBG0+bf2PnOnNgbSx3V/7aa7r52U7fA7rNxye9pqc1s/hdM2RAzD8joos3crQPkB+CPntGRyhYWOhS59cLQPVdD2Wu4UG6zGMwOIoYLrA/hHxjKpnX/13qX+PaR7n37YiVGneXpkY/wtAytzjOExps6euRUJS5djebPpn6HkKyITMAt8V563apOLWK6NFBfmlVC5Quq6jsfyO22Q4P5vpL3Py1oVAbka06fH7cfJT9MpUFRzj9Y3gnulmq86mWFkK0ceJ1/JjaJ71+DklMhnDIIvi6krGk/BhXc+xZYboQ9FGzOezU6qeddPlzmlrhu+0opA=
        on:
          tags: true
          repo: embermap/ember-data-storefront

  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
